### ISSUE TITLE
Error running demo

### ISSUE THREAD

**Issue by jorvis** [bioboxes/command-line-interface#102]
I tried using Bioboxes for the first time using the demo commands.  It ran for about 45 seconds before erroring with the trace below:

```
$ pip2 install --user biobox_cli
[ lots of output, ran successfully ]

$ /home/jorvis/.local/bin/biobox run short_read_assembler bioboxes/megahit --input SRS015996.denovo_duplicates_marked.trimmed.1.fastq --output megahit_test_dir1only
Traceback (most recent call last):
  File "/home/jorvis/.local/bin/biobox", line 9, in <module>
    biobox.run()
  File "/home/jorvis/.local/lib/python2.7/site-packages/biobox_cli/main.py", line 30, in run
    util.select_module("command", opts["<command>"]).run(args)
  File "/home/jorvis/.local/lib/python2.7/site-packages/biobox_cli/command/run.py", line 26, in run
    ctnr = bbx.run(argv)
  File "/home/jorvis/.local/lib/python2.7/site-packages/biobox_cli/biobox_helper.py", line 42, in run
    self.after_run(output, output_dir)
  File "/home/jorvis/.local/lib/python2.7/site-packages/biobox_cli/biobox_type/short_read_assembler.py", line 36, in after_run
    biobox_output = fle.get_biobox_file_contents(host_dst_dir)
  File "/home/jorvis/.local/lib/python2.7/site-packages/biobox_cli/biobox_file.py", line 9, in get_biobox_file_contents
    with open(os.path.join(dir_, 'biobox.yaml'), 'r') as f:
IOError: [Errno 2] No such file or directory: '/tmp/tmpbSgC_Y/biobox.yaml'
```

**Comment by michaelbarton** [comment]
Thanks for the bug report Jorvis. Could you tell me what operating system you are using?
Could you also provide the logs of the container you ran? E.g. docker logs ...

**Comment by michaelbarton** [comment]
The output of `docker info` would also be helpful. Thanks.

**Comment by jorvis** [comment]
I'll try to reproduce.  I actually just upgraded that laptop to Ubuntu 16.04, so the environment has now changed.

**Comment by michaelbarton** [comment]
Ok thank you. If you can diagnose the bug that would be very helpful. We
run unit and feature tests on debian so if you do find the cause of the
problem we can try to update the biobox_cli to cover this.

**Comment by jorvis** [comment]
I don't want to drop the ball here, but I did test again on my new OS (Ubuntu 16.04) with a new install of bioboxes and the same issue happened:

```
$ biobox run short_read_assembler bioboxes/megahit --input SRS015996.denovo_duplicates_marked.trimmed.1.fastq --output megahit_test_dir1only
Traceback (most recent call last):
  File "/usr/local/bin/biobox", line 9, in <module>
    biobox.run()
  File "/usr/local/lib/python2.7/dist-packages/biobox_cli/main.py", line 30, in run
    util.select_module("command", opts["<command>"]).run(args)
  File "/usr/local/lib/python2.7/dist-packages/biobox_cli/command/run.py", line 26, in run
    ctnr = bbx.run(argv)
  File "/usr/local/lib/python2.7/dist-packages/biobox_cli/biobox_helper.py", line 42, in run
    self.after_run(output, output_dir)
  File "/usr/local/lib/python2.7/dist-packages/biobox_cli/biobox_type/short_read_assembler.py", line 36, in after_run
    biobox_output = fle.get_biobox_file_contents(host_dst_dir)
  File "/usr/local/lib/python2.7/dist-packages/biobox_cli/biobox_file.py", line 9, in get_biobox_file_contents
    with open(os.path.join(dir_, 'biobox.yaml'), 'r') as f:
IOError: [Errno 2] No such file or directory: '/tmp/tmph9K5zf/biobox.yaml'
```

What exact log can I help by sending?

**Comment by michaelbarton** [comment]
Could you paste the output of `docker logs ...` using the ID of the
bioboxes/megahit container? You can get this ID using `docker ps -a`.

Thanks for following up.

**Comment by jorvis** [comment]
I had tried 'docker ps' and got nothing before posting, but it seems the -a was the critical missing option.  OK, the output was:

```
gzip: /bbx/mount/oB4AnDJr8RR2qrrnq3W0V57z/SRS015996.denovo_duplicates_marked.trimmed.1.fastq: not in gzip format
max_read_len must be greater than 1.
```

So it appears the megahit biobox **requires** the input to be in compressed format. It worked after I changed this.  Is there a way to get the error to propagate up rather than just showing the YAML error?

**Comment by michaelbarton** [comment]
Thanks for posting the log and working out what the problem was.

Yes, I agree it would be ideal if the error message was more descriptive. Generally when the biobox.yaml cannot be found it means that something has gone wrong inside the container. A more descriptive error message from the would be useful, perhaps directing the user to look at the container logs if there is a non-zero exit code?

**Comment by michaelbarton** [comment]
Also to follow up on .gz requirement for the input files, this is one we have added to the biobox specification. This is for expediency as the less input formats we have to support the easier it is to create more bioboxes as less time is required for each.
